modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = "https://github.com/FrixionCoffee/ProcessRunnerMod/issues"
license = "Creative Commons Zero v1.0 Universal"

[[mods]]
modId = "processrunnermod"
version = "${version}"
displayName = "Process Runner Mod"
authors = "SugarCoffee"
description = '''
Play music when the title of the game is displayed. It runnable both fabric and forge.
Forum URL: https://example.com/
Github: https://github.com/FrixionCoffee/ProcessRunnerMod
'''
#logoFile = ""

[[dependencies.processrunnermod]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.processrunnermod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.processrunnermod]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"